ERROR - 2022-03-21 23:57:36 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-21 23:57:36 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
