ERROR - 2022-05-11 16:46:51 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-11 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT `m`.*, `...', Array, false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Models\MascotaModel.php(35): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Mascota.php(53): App\Models\MascotaModel->getMascotas()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Mascota->index()
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mascota))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:06:38 --> There is no data to update.
#0 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(Array, 'update')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Animal.php(50): CodeIgniter\Model->update('4', Array)
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Animal->update('4')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:06:41 --> There is no data to update.
#0 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(Array, 'update')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Animal.php(50): CodeIgniter\Model->update('4', Array)
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Animal->update('4')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:07:01 --> There is no data to update.
#0 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(Array, 'update')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Animal.php(50): CodeIgniter\Model->update('4', Array)
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Animal->update('4')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:07:36 --> There is no data to update.
#0 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(Array, 'update')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Animal.php(50): CodeIgniter\Model->update('4', Array)
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Animal->update('4')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-11 17:10:04 --> There is no data to update.
#0 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\jesus\Documents\GitHub\vet\system\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray(Array, 'update')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Animal.php(50): CodeIgniter\Model->update('4', Array)
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Animal->update('4')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Animal))
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-05-11 17:47:28 --> Unknown column 'c.idUsuario' in 'on clause'
CRITICAL - 2022-05-11 17:47:28 --> Call to a member function getResultArray() on bool
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Cita.php(36): App\Models\CitaModel->getCitas()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Cita->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-11 17:47:32 --> Unknown column 'c.idUsuario' in 'on clause'
CRITICAL - 2022-05-11 17:47:32 --> Call to a member function getResultArray() on bool
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Cita.php(36): App\Models\CitaModel->getCitas()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Cita->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-11 17:48:46 --> Unknown column 'c.idUsuario' in 'on clause'
CRITICAL - 2022-05-11 17:48:46 --> Call to a member function getResultArray() on bool
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Cita.php(36): App\Models\CitaModel->getCitas()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Cita->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:05:59 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:23:03 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:23:12 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:23:13 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:41:40 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:41:51 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:41:58 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:42:18 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:42:23 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:42:31 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:43:00 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:44:57 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:46:36 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 18:48:10 --> Call to a member function getValue() on null
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(14): App\Controllers\Auth->verifyToken()
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-05-11 18:53:24 --> Unknown column 'usuario' in 'where clause'
CRITICAL - 2022-05-11 18:53:24 --> Unknown column 'usuario' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-11 18:55:17 --> Unknown column 'usuario' in 'where clause'
CRITICAL - 2022-05-11 18:55:17 --> Unknown column 'usuario' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-11 18:55:39 --> Unknown column 'usuario' in 'where clause'
CRITICAL - 2022-05-11 18:55:39 --> Unknown column 'usuario' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-11 18:56:50 --> Unknown column 'usuario' in 'where clause'
CRITICAL - 2022-05-11 18:56:50 --> Unknown column 'usuario' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-11 18:56:58 --> Unknown column 'usuario' in 'where clause'
CRITICAL - 2022-05-11 18:56:58 --> Unknown column 'usuario' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-05-11 19:00:07 --> Unknown column 'telefno' in 'where clause'
CRITICAL - 2022-05-11 19:00:07 --> Unknown column 'telefno' in 'where clause'
#0 C:\Users\jesus\Documents\GitHub\vet\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Models\UsuarioModel.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(27): App\Models\UsuarioModel->obtenerUsuario(Array)
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-11 19:06:12 --> Invalid file: usuario/auth.php
#0 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('usuario/auth.ph...')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/auth', Array, true)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\login.php(29): view('usuario/auth')
#3 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#4 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/login', Array, true)
#6 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(23): view('usuario/login')
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#9 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-11 19:06:40 --> Invalid file: usuario/auth.php
#0 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('usuario/auth.ph...')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/auth', Array, true)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\login.php(29): view('usuario/auth')
#3 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#4 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/login', Array, true)
#6 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(23): view('usuario/login')
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->login()
#8 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#9 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-11 19:25:29 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(32): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:25:29 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(32): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:25:29 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(32): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:25:29 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(32): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:12 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:15 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:15 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:16 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:33 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:33 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:33 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:26:33 --> Undefined variable: usuarios
#0 C:\Users\jesus\Documents\GitHub\vet\app\Views\usuario\index.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\Users\\jesus\\...', 61, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(210): include('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(1089): CodeIgniter\View\View->render('usuario/index', Array, true)
#4 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(28): view('usuario/index')
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#6 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-11 19:37:14 --> Array to string conversion
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\Users\\jesus\\...', 40, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 19:37:47 --> count(): Parameter must be an array or an object that implements Countable
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'C:\\Users\\jesus\\...', 37, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(37): count(NULL)
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 19:37:54 --> Array to string conversion
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\Users\\jesus\\...', 40, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 19:39:02 --> count(): Parameter must be an array or an object that implements Countable
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'C:\\Users\\jesus\\...', 37, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(37): count(NULL)
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 19:39:54 --> count(): Parameter must be an array or an object that implements Countable
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'C:\\Users\\jesus\\...', 37, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(37): count(NULL)
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 19:40:01 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(39): redirect('http://vet.loc/...')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:42:04 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(39): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:42:35 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(43): redirect('usuario/index', Array)
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:43:39 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(41): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:01 --> count(): Parameter must be an array or an object that implements Countable
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'C:\\Users\\jesus\\...', 37, Array)
#1 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(37): count(NULL)
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-11 19:45:08 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(41): redirect('mascota/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:34 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(37): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:42 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:42 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:42 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:43 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:43 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:43 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:52 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:45:58 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:49:19 --> Too few arguments to function CodeIgniter\Router\RouteCollection::get(), 1 passed in C:\Users\jesus\Documents\GitHub\vet\app\Config\Routes.php on line 39 and at least 2 expected
#0 C:\Users\jesus\Documents\GitHub\vet\app\Config\Routes.php(39): CodeIgniter\Router\RouteCollection->get('usuario')
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(713): require('C:\\Users\\jesus\\...')
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-11 19:50:32 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 19:50:52 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(36): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:02:03 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(40): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:02:30 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(42): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:02:35 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(42): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:02:51 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(42): redirect('usuario/index')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:20:03 -->  route cannot be found while reverse-routing.
#0 C:\Users\jesus\Documents\GitHub\vet\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\Users\jesus\Documents\GitHub\vet\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(43): redirect('refresh')
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#4 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-11 20:20:25 --> Argument 2 passed to CodeIgniter\HTTP\RedirectResponse::to() must be of the type int or null, string given, called in C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php on line 43
#0 C:\Users\jesus\Documents\GitHub\vet\app\Controllers\Usuario.php(43): CodeIgniter\HTTP\RedirectResponse->to('http://vet.loc/...', 'refresh')
#1 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->auth()
#2 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\Users\jesus\Documents\GitHub\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\Users\jesus\Documents\GitHub\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
